\c support_insights

-- Create schemas in SUPPORT_INSIGHTS if they do not exist
CREATE SCHEMA IF NOT EXISTS ds;
CREATE SCHEMA IF NOT EXISTS info;
CREATE SCHEMA IF NOT EXISTS aud;
CREATE SCHEMA IF NOT EXISTS lnd;
CREATE SCHEMA IF NOT EXISTS cdc;
CREATE SCHEMA IF NOT EXISTS prs;
CREATE SCHEMA IF NOT EXISTS pre_dm;
CREATE SCHEMA IF NOT EXISTS dm;
CREATE SCHEMA IF NOT EXISTS dwh;
CREATE SCHEMA IF NOT EXISTS vw;
