\c support_insights

-- INSERT DATA INTO DS.SOURCES
INSERT INTO DS.SOURCES (SOURCE_NAME, SOURCE_FILE_TYPE, DATALOAD_STRATEGY, LAST_LOADED_RECORD_ID, DESCRIPTION)
VALUES 
    ('CLIENT_ALPHA', 'JSON', 'INCREMENTAL', NULL, 'CUSTOMER SUPPORT DATA FROM CLIENT_ALPHA SOURCE'),
    ('CLIENT_BETA', 'XML', 'INCREMENTAL', NULL, 'CUSTOMER SUPPORT DATA FROM CLIENT_BETA SOURCE'),
    ('CLIENT_GAMMA', 'CSV', 'INCREMENTAL', NULL, 'CUSTOMER SUPPORT DATA FROM CLIENT_GAMMA SOURCE');

-- INSERT DATA INTO DS.SUPPORT_AREAS
-- CLIENT_ALPHA
INSERT INTO DS.SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION)
VALUES 
    ('ORDER ISSUES', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'SUPPORT AREA FROM CLIENT_ALPHA'),
    ('PRODUCT INQUIRIES', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'SUPPORT AREA FROM CLIENT_ALPHA'),
    ('SHIPPING & DELIVERY', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'SUPPORT AREA FROM CLIENT_ALPHA'),
    ('ACCOUNT & SECURITY', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'SUPPORT AREA FROM CLIENT_ALPHA'),
    ('PAYMENTS & BILLING', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'SUPPORT AREA FROM CLIENT_ALPHA'),
    ('RETURNS & REFUNDS', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'SUPPORT AREA FROM CLIENT_ALPHA'),
    ('TECHNICAL SUPPORT', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'SUPPORT AREA FROM CLIENT_ALPHA'),
    ('PROMOTIONS & DISCOUNTS', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'SUPPORT AREA FROM CLIENT_ALPHA'),
    ('PRIME MEMBERSHIP', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'SUPPORT AREA FROM CLIENT_ALPHA'),
    ('MARKETPLACE & THIRD-PARTY SELLERS', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'SUPPORT AREA FROM CLIENT_ALPHA');

-- CLIENT_BETA
INSERT INTO DS.SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION)
VALUES 
    ('RIDE ISSUES', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'SUPPORT AREA FROM CLIENT_BETA'),
    ('DRIVER/PASSENGER CONCERNS', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'SUPPORT AREA FROM CLIENT_BETA'),
    ('PAYMENTS & BILLING', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'SUPPORT AREA FROM CLIENT_BETA'),
    ('SAFETY & SECURITY', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'SUPPORT AREA FROM CLIENT_BETA'),
    ('ACCOUNT & PROFILE MANAGEMENT', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'SUPPORT AREA FROM CLIENT_BETA'),
    ('PROMOTIONS & DISCOUNT', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'SUPPORT AREA FROM CLIENT_BETA'),
    ('DRIVER SUPPORT', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'SUPPORT AREA FROM CLIENT_BETA'),
    ('TECHNICAL SUPPORT', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'SUPPORT AREA FROM CLIENT_BETA'),
    ('CLIENT_BETA EATS', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'SUPPORT AREA FROM CLIENT_BETA'),
    ('ACCESIBILITY SUPPORT', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'SUPPORT AREA FROM CLIENT_BETA');

-- CLIENT_GAMMA
INSERT INTO DS.SUPPORT_AREAS (SUPPORT_AREA_NAME, SOURCE_ID, DESCRIPTION)
VALUES 
    ('ACCOUNT MANAGEMENT', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'SUPPORT AREA FROM CLIENT_GAMMA'),
    ('TECHNICAL SUPPORT', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'SUPPORT AREA FROM CLIENT_GAMMA'),
    ('SUPPORT OUTAGES', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'SUPPORT AREA FROM CLIENT_GAMMA'),
    ('NEW CUSTOMER ONBOARDING', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'SUPPORT AREA FROM CLIENT_GAMMA'),
    ('MOBILE & WIRELESS SERVICES', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'SUPPORT AREA FROM CLIENT_GAMMA'),
    ('HOME SERVICES', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'SUPPORT AREA FROM CLIENT_GAMMA'),
    ('PROMOTIONS & DISCOUNTS', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'SUPPORT AREA FROM CLIENT_GAMMA'),
    ('SECURITY & PRIVACY', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'SUPPORT AREA FROM CLIENT_GAMMA'),
    ('BUSINESS SERVICES', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'SUPPORT AREA FROM CLIENT_GAMMA'),
    ('LOYALTY & RETENTIONS', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'SUPPORT AREA FROM CLIENT_GAMMA');

-- INSERT DATA INTO DS.AGENTS
-- CLIENT_ALPHA
INSERT INTO DS.AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID)
VALUES 
    ('JOHN', 'A.', 'DOE', 'JDOE', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA')),
    ('JANE', 'B.', 'SMITH', 'JSMITH', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA')),
    ('ALICE', 'C.', 'JOHNSON', 'AJOHNSON', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA')),
    ('BOB', 'D.', 'WILLIAMS', 'BWILLIAMS', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA')),
    ('CHARLIE', 'E.', 'BROWN', 'CBROWN', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA')),
    ('DAVID', 'F.', 'JONES', 'DJONES', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA')),
    ('EVE', 'G.', 'GARCIA', 'EGARCIA', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA')),
    ('FRANK', 'H.', 'MARTINEZ', 'FMARTINEZ', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA')),
    ('GRACE', 'I.', 'HERNANDEZ', 'GHERNANDEZ', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA')),
    ('HANK', 'J.', 'LOPEZ', 'HLOPEZ', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'));

-- CLIENT_BETA
INSERT INTO DS.AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID)
VALUES 
    ('IVY', 'K.', 'GONZALEZ', 'IGONZALEZ', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA')),
    ('JACK', 'L.', 'WILSON', 'JWILSON', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA')),
    ('KARA', 'M.', 'ANDERSON', 'KANDERSON', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA')),
    ('LEO', 'N.', 'THOMAS', 'LTHOMAS', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA')),
    ('MIA', 'O.', 'TAYLOR', 'MTAYLOR', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA')),
    ('NATE', 'P.', 'MOORE', 'NMOORE', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA')),
    ('OLIVIA', 'Q.', 'JACKSON', 'OJACKSON', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA')),
    ('PAUL', 'R.', 'WHITE', 'PWHITE', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA')),
    ('QUINN', 'S.', 'HARRIS', 'QHARRIS', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA')),
    ('RYAN', 'T.', 'MARTIN', 'RMARTIN', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'));

-- CLIENT_GAMMA
INSERT INTO DS.AGENTS (FIRST_NAME, MIDDLE_NAME, LAST_NAME, PSEUDO_CODE, SOURCE_ID)
VALUES 
    ('SARA', 'U.', 'THOMPSON', 'STHOMPSON', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA')),
    ('TOM', 'V.', 'GARCIA', 'TGARCIA', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA')),
    ('UMA', 'W.', 'MARTINEZ', 'UMARTINEZ', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA')),
    ('VICTOR', 'X.', 'HERNANDEZ', 'VHERNANDEZ', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA')),
    ('WENDY', 'Y.', 'LOPEZ', 'WLOPEZ', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA')),
    ('XANDER', 'Z.', 'GONZALEZ', 'XGONZALEZ', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA')),
    ('YARA', 'A.', 'WILSON', 'YWILSON', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA')),
    ('ZANE', 'B.', 'ANDERSON', 'ZANDERSON', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA')),
    ('ABBY', 'C.', 'THOMAS', 'ATHOMAS', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA')),
    ('EDGAR', 'D.', 'JONES', 'EJONES', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'));

-- INSERT DATA INTO DS.CUSTOMER_TYPES
-- CLIENT_ALPHA
INSERT INTO DS.CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION)
VALUES 
    ('FIRST-TIME SHOPPER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'CUSTOMER TYPE FROM CLIENT_ALPHA SOURCE'),
    ('FREQUENT BUYER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'CUSTOMER TYPE FROM CLIENT_ALPHA SOURCE'),
    ('PRIME MEMBER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'CUSTOMER TYPE FROM CLIENT_ALPHA SOURCE'),
    ('HIGH-SPENDER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'CUSTOMER TYPE FROM CLIENT_ALPHA SOURCE'),
    ('BUDGET SHOPPER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'CUSTOMER TYPE FROM CLIENT_ALPHA SOURCE'),
    ('BUSINESS BUYER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'CUSTOMER TYPE FROM CLIENT_ALPHA SOURCE'),
    ('TECH-SAVVY BUYER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'CUSTOMER TYPE FROM CLIENT_ALPHA SOURCE'),
    ('GIFT GIVER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'CUSTOMER TYPE FROM CLIENT_ALPHA SOURCE'),
    ('RETURNS & REFUND SEEKER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'CUSTOMER TYPE FROM CLIENT_ALPHA SOURCE'),
    ('COMPLAINT-FOCUSED CUSTOMER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'CUSTOMER TYPE FROM CLIENT_ALPHA SOURCE');
	
-- CLIENT_BETA
INSERT INTO DS.CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION)
VALUES 
    ('FIRST-TIME RIDER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'CUSTOMER TYPE FROM CLIENT_BETA SOURCE'),
    ('FREQUENT RIDER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'CUSTOMER TYPE FROM CLIENT_BETA SOURCE'),
    ('COMMUTER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'CUSTOMER TYPE FROM CLIENT_BETA SOURCE'),
    ('TRAVELER/TOURIST', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'CUSTOMER TYPE FROM CLIENT_BETA SOURCE'),
    ('CLIENT_BETA EATS CUSTOMER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'CUSTOMER TYPE FROM CLIENT_BETA SOURCE'),
    ('CORPORATE RIDER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'CUSTOMER TYPE FROM CLIENT_BETA SOURCE'),
    ('DRIVER-PARTNER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'CUSTOMER TYPE FROM CLIENT_BETA SOURCE'),
    ('PROMO-SEEKER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'CUSTOMER TYPE FROM CLIENT_BETA SOURCE'),
    ('SAFETY-CONSCIOUS RIDER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'CUSTOMER TYPE FROM CLIENT_BETA SOURCE'),
    ('ACCESSIBILITY-FOCUSED CUSTOMER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'CUSTOMER TYPE FROM CLIENT_BETA SOURCE');

-- CLIENT_GAMMA
INSERT INTO DS.CUSTOMER_TYPES (CUSTOMER_TYPE_NAME, SOURCE_ID, DESCRIPTION)
VALUES 
    ('NEW CUSTOMER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'CUSTOMER TYPE FROM CLIENT_GAMMA SOURCE'),
    ('LONG-TERM CUSTOMER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'CUSTOMER TYPE FROM CLIENT_GAMMA SOURCE'),
    ('TECH-SAVVY USER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'CUSTOMER TYPE FROM CLIENT_GAMMA SOURCE'),
    ('SENIOR CITIZEN', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'CUSTOMER TYPE FROM CLIENT_GAMMA SOURCE'),
    ('BUSINESS OWNER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'CUSTOMER TYPE FROM CLIENT_GAMMA SOURCE'),
    ('FAMILY PLAN MANAGER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'CUSTOMER TYPE FROM CLIENT_GAMMA SOURCE'),
    ('FREQUENT TRAVELER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'CUSTOMER TYPE FROM CLIENT_GAMMA SOURCE'),
    ('BUDGET-CONSCIOUS CUSTOMER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'CUSTOMER TYPE FROM CLIENT_GAMMA SOURCE'),
    ('HEAVY DATA USER', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'CUSTOMER TYPE FROM CLIENT_GAMMA SOURCE'),
    ('DEVICE ENTHUSIAST', (SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'CUSTOMER TYPE FROM CLIENT_GAMMA SOURCE');