\c support_insights

-- INSERT DATA INTO INFO.OBJECT_TYPES
INSERT INTO INFO.OBJECT_TYPES (OBJECT_TYPE_CODE, DESCRIPTION)
VALUES 
    ('DATA MART TABLE', 'TABLE THAT STORES ACTUAL DATA FOR WHICH THE DATABASE HAS BEEN CREATED'),
    ('DATA STANDARD TABLE', 'TABLE THAT DEFINES THE STANDARD VALUES FOR A COLUMN OF THE DATA MART TABLE'),
    ('DATA AUDIT TABLE', 'TABLE THAT STORES AUDIT INFORMATION OF SPECIFIC ACTIONS ON DATA MART TABLE'),
    ('DATABASE INFORMATION TABLE', 'TABLE THAT STORES THE DATABASE RELATED INFORMATION'),
    ('SOURCE LANDING TABLE', 'TABLE THAT STORES THE RAW DATA FROM SOURCE'),
    ('SOURCE HISTORY DATA TABLE', 'TABLE THAT STORES THE HISTORICAL DATA FROM SOURCE IN SCD 2'),
    ('SOURCE CDC DATA TABLE', 'TABLE THAT STORES THE CHANGE DATA CAPTURE FROM SOURCE BEFORE TRANSFORMATIONS'),
    ('DWH HISTORY TABLE', 'TABLE THAT STORES HISTORICAL SCD 2 DATA OF A SCD 1 TABLE');

-- INSERT DATA INTO INFO.OBJECT_LOAD_STRATEGIES
INSERT INTO INFO.OBJECT_LOAD_STRATEGIES (OBJECT_LOAD_STRATEGY_CODE, DESCRIPTION)
VALUES 
    ('AIRFLOW BATCH', 'THE TABLE SHALL BE LOADED USING AN AIRFLOW BATCH FLOW WITH PYSPARK ETL'),
    ('MANUAL DML', 'THE TABLE SHALL BE LOADED USING A DML STATEMENT MANUALLY'),
    ('TABLE TRIGGER', 'THE TABLE SHALL BE LOADED USING A TABLE TRIGGER DEFINED ON THE UPSTREAM TABLE');

-- INSERT DATA INTO INFO.DATA_DICTIONARY
-- CLIENT_ALPHA
INSERT INTO INFO.DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE)
VALUES 
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'RECORD_ID', 'INTEGER', 'SEQUENCE GENERATED VALUE (UNIQUE)', 'PRIMARY KEY OF THE SUPPORT DATA', '1'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'INTERACTION_ID', 'INTEGER', 'SEQUENCE GENERATED VALUE (CAN REPEAT)', 'UNIQUE IDENTIFIER FOR AN INTERACTION', '1'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'SUPPORT_CATEGORY', 'STRING', '"ORDER ISSUES", "PRODUCT INQUIRIES", "SHIPPING & DELIVERY", "ACCOUNT & SECURITY", "PAYMENTS & BILLING", "RETURNS & REFUNDS", "TECHNICAL SUPPORT", "PROMOTIONS & DISCOUNTS", "PRIME MEMBERSHIP", "MARKETPLACE & THIRD-PARTY SELLERS"', 'TYPE OF SUPPORT REQUIRED BY THE USER', 'ORDER ISSUES'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'AGENT_PSEUDO_NAME', 'STRING', '"JDOE", "JSMITH", "AJOHNSON", "BWILLIAMS", "CBROWN", "DJONES", "EGARCIA", "FMARTINEZ", "GHERNANDEZ", "HLOPEZ"', 'CODE NAME OF THE AGENT WHO HANDLED THE INTERACTION', 'JDOE'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'CONTACT_DATE', 'DATETIME', 'DATES AFTER 2021 JAN', 'DATE OF THE INTERACTION IN DD/MM/YYYY HH:MI:SS FORMAT', '01/01/2021 00:00:00'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'INTERACTION_STATUS', 'STRING', '"COMPLETED", "DROPPED", "TRANSFERRED"', 'STATUS OF THE CUSTOMER SUPPORT INTERACTION', 'COMPLETED'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'INTERACTION_TYPE', 'STRING', '"CALL", "CHAT"', 'TYPE OF INTERACTION WITH THE USER', 'CALL'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'TYPE_OF_CUSTOMER', 'STRING', '"FIRST-TIME SHOPPER", "FREQUENT BUYER", "PRIME MEMBER", "HIGH-SPENDER", "BUDGET SHOPPER", "BUSINESS BUYER", "TECH-SAVVY BUYER", "GIFT GIVER", "RETURNS & REFUND SEEKER", "COMPLAINT-FOCUSED CUSTOMER"', 'INTERNAL CUSTOMER TYPE', 'FIRST-TIME SHOPPER'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'INTERACTION_DURATION', 'INTEGER', 'POSITIVE INTEGERS', 'DURATION OF THE INTERACTION WITH CUSTOMER IN SECONDS', '120'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'TOTAL_TIME', 'INTEGER', 'POSITIVE INTEGERS', 'TOTAL TIME TAKEN TO COMPLETE THE INTERACTION AND ANY WORK RELATED TO INTERACTION AFTER CALL IN SECONDS', '150'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'STATUS_OF_CUSTOMER_INCIDENT', 'STRING', '"RESOLVED", "PENDING RESOLUTION", "PENDING CUSTOMER UPDATE", "WORK IN PROGRESS", "TRANSFERRED TO ANOTHER QUEUE"', 'STATUS OF THE CUSTOMERS SUPPORT QUESTION', 'RESOLVED'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'RESOLVED_IN_FIRST_CONTACT', 'STRING', '"YES", "NO"', 'THIS SAYS IF THE RESOLUTION HAS BEEN PROVIDED IN THE FIRST CONTACT', 'YES'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'SOLUTION_TYPE', 'STRING', '"SELF-HELP OPTION", "SUPPORT TEAM INTERVENTION"', 'THE TYPE OF RESOLUTION PROVIDED TO THE CUSTOMER', 'SELF-HELP OPTION'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_ALPHA'), 'RATING', 'INTEGER', '1 - 10', 'RATING GIVEN BY THE CUSTOMER FOR THE INTERACTION', '10');

-- CLIENT_BETA
INSERT INTO INFO.DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE)
VALUES
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'SUPPORT_IDENTIFIER', 'INTEGER', 'SEQUENCE GENERATED VALUE', 'UNIQUE IDENTIFIER FOR A SUPPORT INTERACTION', '1'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'CONTACT_REGARDING', 'STRING', '"RIDE ISSUES", "DRIVER/PASSENGER CONCERNS", "PAYMENTS & BILLING", "SAFETY & SECURITY", "ACCOUNT & PROFILE MANAGEMENT", "PROMOTIONS & DISCOUNT", "DRIVER SUPPORT", "TECHNICAL SUPPORT", "CLIENT_BETA EATS", "ACCESIBILITY SUPPORT"', 'TYPE OF SUPPORT REQUIRED BY THE USER', 'RIDE ISSUES'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'AGENT_CODE', 'STRING', '"IGONZALEZ", "JWILSON", "KANDERSON", "LTHOMAS", "MTAYLOR", "NMOORE", "OJACKSON", "PWHITE", "QHARRIS", "RMARTIN"', 'CODE NAME OF THE AGENT WHO HANDLED THE INTERACTION', 'IGONZALEZ'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'DATE_OF_INTERACTION', 'DATE', 'DATES AFTER 2021 JAN', 'DATE IN YYYYMMDD FORMAT', '20210401'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'STATUS_OF_INTERACTION', 'STRING', '"INTERACTION COMPLETED", "CUSTOMER DROPPED", "TRANSFERRED"', 'STATUS OF THE CUSTOMER SUPPORT INTERACTION', 'INTERACTION COMPLETED'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'TYPE_OF_INTERACTION', 'STRING', '"CALL", "CHAT"', 'TYPE OF INTERACTION WITH THE USER', 'CHAT'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'CUSTOMER_TYPE', 'STRING', '"FIRST-TIME RIDER", "FREQUENT RIDER", "COMMUTER", "TRAVELER/TOURIST", "CLIENT_BETA EATS CUSTOMER", "CORPORATE RIDER", "DRIVER-PARTNER", "PROMO-SEEKER", "SAFETY-CONSCIOUS RIDER", "ACCESSIBILITY-FOCUSED CUSTOMER"', 'INTERNAL CUSTOMER TYPE', 'PROMO-SEEKER'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'CONTACT_DURATION', 'TIMESTAMP', 'POSITIVE TIMESTAMPS', 'DURATION OF THE INTERACTION WITH CUSTOMER IN TIMESTAMP FORMAT', '00:02:00'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'AFTER_CONTACT_WORK_TIME', 'TIMESTAMP', 'POSITIVE TIMESTAMPS', 'ANY WORK RELATED TO INTERACTION AFTER CALL IN TIMESTAMP FORMAT', '00:01:00'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'INCIDENT_STATUS', 'STRING', '"RESOLVED", "PENDING RESOLUTION", "PENDING CUSTOMER UPDATE", "WORK IN PROGRESS", "TRANSFERRED TO ANOTHER QUEUE"', 'STATUS OF THE CUSTOMERS SUPPORT QUESTION', 'RESOLVED'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'FIRST_CONTACT_SOLVE', 'BOOLEAN', '"1", "FALSE"', 'THIS SAYS IF THE RESOLUTION HAS BEEN PROVIDED IN THE FIRST CONTACT', '1'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'TYPE_OF_RESOLUTION', 'STRING', '"SELF-HELP OPTION", "SUPPORT TEAM INTERVENTION"', 'THE TYPE OF RESOLUTION PROVIDED TO THE CUSTOMER', 'SELF-HELP OPTION'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'SUPPORT_RATING', 'INTEGER', '1 - 5', 'RATING GIVEN BY THE CUSTOMER FOR THE INTERACTION', '5'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_BETA'), 'TIME_STAMP', 'TIMESTAMP', 'TIMESTAMP VALUES', 'TIMESTAMP OF THE RECORD CREATION', '01/01/2024 00:00:00');

-- CLIENT_GAMMA
INSERT INTO INFO.DATA_DICTIONARY (SOURCE_ID, FIELD_NAME, DATA_TYPE, VALUES_ALLOWED, DESCRIPTION, EXAMPLE)
VALUES
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'TICKET_IDENTIFIER', 'INTEGER', 'SEQUENCE GENERATED INTEGER VALUES', 'UNIQUE IDENTIFIER FOR A SUPPORT INTERACTION', '1'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'SUPPORT_CATEGORY', 'STRING', '"ACCOUNT MANAGEMENT", "TECHNICAL SUPPORT", "SUPPORT OUTAGES", "NEW CUSTOMER ONBOARDING", "MOBILE & WIRELESS SERVICES", "HOME SERVICES", "PROMOTIONS & DISCOUNTS", "SECURITY & PRIVACY", "BUSINESS SERVICES", "LOYALTY & RETENTIONS"', 'TYPE OF SUPPORT REQUIRED BY THE USER', 'ACCOUNT MANAGEMENT'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'AGENT_NAME', 'STRING', '"STHOMPSON", "TGARCIA", "UMARTINEZ", "VHERNANDEZ", "WLOPEZ", "XGONZALEZ", "YWILSON", "ZANDERSON", "ATHOMAS", "EDJONES"', 'CODE NAME OF THE AGENT WHO HANDLED THE INTERACTION', 'STHOMPSON'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'DATE_OF_CALL', 'DATETIME', 'DATES AFTER 2021 JAN', 'DATE IN MMDDYYYYHHMISS FORMAT', '01012024000000'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'CALL_STATUS', 'STRING', '"CALL COMPLETED", "CALL DROPPED", "CALL TRANSFERRED"', 'STATUS OF THE CUSTOMER SUPPORT INTERACTION', 'CALL COMPLETED'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'CALL_TYPE', 'STRING', '"CALL", "CHAT"', 'TYPE OF INTERACTION WITH THE USER', 'CALL'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'TYPE_OF_CUSTOMER', 'STRING', '"NEW CUSTOMER", "LONG-TERM CUSTOMER", "TECH-SAVVY USER", "SENIOR CITIZEN", "BUSINESS OWNER", "FAMILY PLAN MANAGER", "FREQUENT TRAVELER", "BUDGET-CONSCIOUS CUSTOMER", "HEAVY DATA USER", "DEVICE ENTHUSIAST"', 'INTERNAL CUSTOMER TYPE', 'NEW CUSTOMER'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'DURATION', 'INTEGER', 'POSITIVE INTEGER', 'DURATION OF THE INTERACTION WITH CUSTOMER IN SECONDS', '120'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'WORK_TIME', 'INTEGER', 'POSITIVE INTEGER', 'ANY WORK RELATED TO INTERACTION AFTER CALL IN SECONDS', '30'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'TICKET_STATUS', 'STRING', '"RESOLVED", "PENDING RESOLUTION", "PENDING CUSTOMER UPDATE", "WORK IN PROGRESS", "TRANSFERRED TO ANOTHER QUEUE"', 'STATUS OF THE CUSTOMERS SUPPORT QUESTION', 'RESOLVED'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'RESOLVED_IN_FIRST_CONTACT', 'INTEGER', '1, 0', 'THIS SAYS IF THE RESOLUTION HAS BEEN PROVIDED IN THE FIRST CONTACT', '1'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'RESOLUTION_CATEGORY', 'STRING', '"SELF-HELP OPTION", "SUPPORT TEAM INTERVENTION"', 'THE TYPE OF RESOLUTION PROVIDED TO THE CUSTOMER', 'SELF-HELP OPTION'),
    ((SELECT SOURCE_ID FROM DS.SOURCES WHERE SOURCE_NAME = 'CLIENT_GAMMA'), 'RATING', 'STRING', '"WORST", "BAD", "NEUTRAL", "GOOD", "BEST"', 'RATING GIVEN BY THE CUSTOMER FOR THE INTERACTION', 'BEST');

-- INSERT DATA INTO INFO.OBJECT_NAMES
INSERT INTO INFO.OBJECT_NAMES (OBJECT_NAME, OBJECT_TYPE_ID, DESCRIPTION, OBJECT_LOAD_STRATEGY_ID)
VALUES 
    ('DS.SOURCES', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DATA STANDARD TABLE'), 'TABLE TO STORE THE INFORMATION OF SOURCES THAT ARE BEING USED IN THE DATA MART', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'MANUAL DML')),
    ('DS.SUPPORT_AREAS', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DATA STANDARD TABLE'), 'TABLE TO STORE THE INFORMATION OF SUPPORT AREAS FROM EACH SOURCE', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'MANUAL DML')),
    ('DS.AGENTS', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DATA STANDARD TABLE'), 'TABLE TO STORE THE INFORMATION OF AGENT NAMES FROM EACH SOURCE', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'MANUAL DML')),
    ('DS.CUSTOMER_TYPES', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DATA STANDARD TABLE'), 'TABLE TO STORE THE INFORMATION OF CUSTOMER TYPES FROM EACH SOURCE', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'MANUAL DML')),
    ('INFO.OBJECT_TYPES', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DATABASE INFORMATION TABLE'), 'TABLE TO STORE THE INFORMATION ON THE TYPES OF TABLES PRESENT IN THE DATABASE', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'MANUAL DML')),
    ('INFO.OBJECT_LOAD_STRATEGIES', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DATABASE INFORMATION TABLE'), 'TABLE TO STORE THE INFORMATION ON HOW A TABLE GETS LOADED WITH DATA', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'MANUAL DML')),
    ('INFO.DATA_DICTIONARY', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DATABASE INFORMATION TABLE'), 'TABLE TO STORE THE INFORMATION ON THE DATA RECEIVED FROM EACH SOURCE', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'MANUAL DML')),
    ('INFO.OBJECT_NAMES', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DATABASE INFORMATION TABLE'), 'TABLE TO STORE THE INFORMATION ON THE TABLES IN THE DATABASE', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'MANUAL DML')),
    ('AUD.DATA_ERROR_HISTORY', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DATA AUDIT TABLE'), 'TABLE TO STORE THE INFORMATION OF ERRORS THAT OCCURRED DURING THE LOAD', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'AIRFLOW BATCH')),
    ('AUD.DAG_RUNS', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DATA AUDIT TABLE'), 'TABLE TO STORE THE INFORMATION OF EACH PYSPARK LOAD EXECUTED', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'AIRFLOW BATCH')),
    ('LND.CLIENT_ALPHA_CS_DATA', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'SOURCE LANDING TABLE'), 'TABLE THAT ACTS AS LANDING AREA OF CLIENT_ALPHA DATA', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'AIRFLOW BATCH')),
    ('LND.CLIENT_BETA_CS_DATA', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'SOURCE LANDING TABLE'), 'TABLE THAT ACTS AS LANDING AREA OF CLIENT_BETA DATA', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'AIRFLOW BATCH')),
    ('LND.CLIENT_GAMMA_CS_DATA', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'SOURCE LANDING TABLE'), 'TABLE THAT ACTS AS LANDING AREA OF CLIENT_GAMMA DATA', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'AIRFLOW BATCH')),
    ('PRS.CLIENT_ALPHA_CS_DATA', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'SOURCE HISTORY DATA TABLE'), 'TABLE THAT ACTS AS STORAGE AREA OF CLIENT_ALPHA DATA', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'AIRFLOW BATCH')),
    ('PRS.CLIENT_BETA_CS_DATA', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'SOURCE HISTORY DATA TABLE'), 'TABLE THAT ACTS AS STORAGE AREA OF CLIENT_BETA DATA', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'AIRFLOW BATCH')),
    ('PRS.CLIENT_GAMMA_CS_DATA', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'SOURCE HISTORY DATA TABLE'), 'TABLE THAT ACTS AS STORAGE AREA OF CLIENT_GAMMA DATA', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'AIRFLOW BATCH')),
    ('CDC.CLIENT_ALPHA_CS_DATA', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'SOURCE CDC DATA TABLE'), 'TABLE THAT ACTS AS CDC AREA OF CLIENT_ALPHA DATA', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'AIRFLOW BATCH')),
    ('CDC.CLIENT_BETA_CS_DATA', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'SOURCE CDC DATA TABLE'), 'TABLE THAT ACTS AS CDC AREA OF CLIENT_BETA DATA', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'AIRFLOW BATCH')),
    ('CDC.CLIENT_GAMMA_CS_DATA', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'SOURCE CDC DATA TABLE'), 'TABLE THAT ACTS AS CDC AREA OF CLIENT_GAMMA DATA', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'AIRFLOW BATCH')),
    ('PRE_DM.CUSTOMER_SUPPORT_STAGE', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DATA MART TABLE'), 'TABLE THAT ACTS AS STAGING AREA OF TRANSFORMED DATA', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'AIRFLOW BATCH')),
    ('DM.CUSTOMER_SUPPORT_FACT', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DATA MART TABLE'), 'TABLE TO STORE THE ACTUAL DATA ON WHICH DASHBOARDS ARE TO BE CREATED', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'AIRFLOW BATCH')),
    ('DWH.DS_SOURCES', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DWH HISTORY TABLE'), 'TABLE THAT ACTS AS DWH STORE FOR DS.SOURCES', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'TABLE TRIGGER')),
    ('DWH.DS_CUSTOMER_TYPES', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DWH HISTORY TABLE'), 'TABLE THAT ACTS AS DWH STORE FOR DS.CUSTOMER_TYPES', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'TABLE TRIGGER')),
    ('DWH.DS_SUPPORT_AREAS', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DWH HISTORY TABLE'), 'TABLE THAT ACTS AS DWH STORE FOR DS.SUPPORT_AREAS', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'TABLE TRIGGER')),
    ('DWH.DS_AGENTS', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DWH HISTORY TABLE'), 'TABLE THAT ACTS AS DWH STORE FOR DS.AGENTS', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'TABLE TRIGGER')),
    ('DWH.INFO_OBJECT_TYPES', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DWH HISTORY TABLE'), 'TABLE THAT ACTS AS DWH STORE FOR INFO.OBJECT_TYPES', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'TABLE TRIGGER')),
    ('DWH.INFO_OBJECT_NAMES', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DWH HISTORY TABLE'), 'TABLE THAT ACTS AS DWH STORE FOR INFO.OBJECT_NAMES', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'TABLE TRIGGER')),
    ('DWH.INFO_OBJECT_LOAD_STRATEGIES', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DWH HISTORY TABLE'), 'TABLE THAT ACTS AS DWH STORE FOR INFO.OBJECT_LOAD_STRATEGIES', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'TABLE TRIGGER')),
    ('DWH.INFO_DATA_DICTIONARY', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DWH HISTORY TABLE'), 'TABLE THAT ACTS AS DWH STORE FOR INFO.DATA_DICTIONARY', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'TABLE TRIGGER')),
    ('DWH.AUD_DAG_RUNS', (SELECT OBJECT_TYPE_ID FROM INFO.OBJECT_TYPES WHERE OBJECT_TYPE_CODE = 'DWH HISTORY TABLE'), 'TABLE THAT ACTS AS DWH STORE FOR AUD.DAG_RUNS', (SELECT OBJECT_LOAD_STRATEGY_ID FROM INFO.OBJECT_LOAD_STRATEGIES WHERE OBJECT_LOAD_STRATEGY_CODE = 'TABLE TRIGGER'));